### ISSUE TITLE
Add support for j2 extension

### ISSUE THREAD

**Issue by poul1x** [HiPhish/jinja.vim#2]
Please, enable jinja syntax highlight when opening `.jinja2` and `.j2` files

**Comment by HiPhish** [comment]
Done. Please report back if there are any further issues.

**Comment by adamency** [comment]
@HiPhish could you please include it in the readme [configuration section](https://github.com/HiPhish/jinja.vim?tab=readme-ov-file#configuration) ? It only mentions `.jinja` extension, so it makes it seem like this actually isn't supported:


> Any file with the extension .jinja will be recognised as a Jinja file.

Anyway, thanks a lot for this plugin !

**Comment by HiPhish** [comment]
Done.
